# Generated by Django 5.2.17 on 2026-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='difficulty',
            field=models.CharField(default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='👾', max_length=255),
        ),
    ]
